//program to create a binary counter using LEDs
//originally only did 0-15, changed code to allow for a fifth LED, counts from 0-31 now
int redLED = 10;
int blueLED = 9;
int greenLED = 8;
int yellowLED = 7;
int whiteLED = 6;
int countSpeed = 1000;

void setup() {
  pinMode(redLED, OUTPUT);
  pinMode(blueLED, OUTPUT);
  pinMode(greenLED, OUTPUT);
  pinMode(yellowLED, OUTPUT);
  pinMode(whiteLED, OUTPUT);
}

void loop() {
digitalWrite(whiteLED,LOW);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, LOW);
  delay(countSpeed);
digitalWrite(redLED, HIGH);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, LOW);
  delay(countSpeed);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, LOW);
  delay(countSpeed);
digitalWrite(redLED, HIGH);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, LOW);
  delay(countSpeed);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, LOW);
  delay(countSpeed);
digitalWrite(redLED, HIGH);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, LOW);
delay(countSpeed);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, LOW);
delay(countSpeed);
digitalWrite(redLED, HIGH);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, LOW);
delay(countSpeed);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, HIGH);
delay(countSpeed);
digitalWrite(redLED, HIGH);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, HIGH);
delay(countSpeed);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, HIGH);
delay(countSpeed);
digitalWrite(redLED, HIGH);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, HIGH);
delay(countSpeed);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, LOW);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, HIGH);
  delay(countSpeed);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, LOW);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, LOW);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
digitalWrite(redLED, LOW);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, LOW);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, LOW);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, LOW);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, LOW);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, LOW);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, LOW);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, LOW);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, LOW);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, LOW);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, HIGH);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, HIGH);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, LOW);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, HIGH);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, LOW);
digitalWrite(yellowLED, HIGH);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, LOW);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, HIGH);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, LOW);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, HIGH);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, LOW);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, HIGH);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
  digitalWrite(redLED, HIGH);
digitalWrite(blueLED, HIGH);
digitalWrite(greenLED, HIGH);
digitalWrite(yellowLED, HIGH);
digitalWrite(whiteLED, HIGH);
  delay(countSpeed);
}
